// Generated by Selenium IDE
package pkg;
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class TestMarchTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  public String waitForWindow(int timeout) {
    try {
      Thread.sleep(timeout);
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
    Set<String> whNow = driver.getWindowHandles();
    Set<String> whThen = (Set<String>) vars.get("window_handles");
    if (whNow.size() > whThen.size()) {
      whNow.removeAll(whThen);
    }
    return whNow.iterator().next();
  }
  @Test
  public void testMarch() {
    driver.get("https://www.google.com/search?q=mobile&sxsrf=APwXEdeLNgmgjFx87TzGj6NAtEt7U0TPvw%3A1686648119361&source=hp&ei=NzWIZIOiE8W-hwPC1JrQCA&iflsig=AOEireoAAAAAZIhDR0pHcvJvBvUrCTx2Afu0ZzIo9v0E&ved=0ahUKEwjDmY3w9b__AhVF32EKHUKqBooQ4dUDCAk&uact=5&oq=mobile&gs_lcp=Cgdnd3Mtd2l6EAMyBwgAEIoFEEMyBwgAEIoFEEMyCAgAEIoFEJECMggIABCKBRCRAjIHCAAQigUQQzIHCAAQigUQQzIHCAAQigUQQzIKCAAQgAQQFBCHAjILCAAQgAQQsQMQgwEyBwgAEIoFEEM6DQgAEIoFELEDEIMBEAo6EQguEIAEELEDEIMBEMcBENEDOgUIABCABDoFCC4QgAQ6CwgAEIoFELEDEIMBOgcIIxCKBRAnOgQIIxAnOggILhCABBCxAzoLCC4QgAQQsQMQgwFQAFidG2DmIWgAcAB4AIAB6gGIAeAIkgEFMC40LjKYAQCgAQE&sclient=gws-wiz");
    driver.manage().window().setSize(new Dimension(1346, 708));
    {
      WebElement element = driver.findElement(By.linkText("Choose area"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    {
      WebElement element = driver.findElement(By.linkText("Images"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.linkText("Images")).click();
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector("#i26 .n9INWd:nth-child(3) .x0Sesd"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    vars.put("window_handles", driver.getWindowHandles());
    driver.findElement(By.cssSelector("#i26 .n9INWd:nth-child(1) .x0Sesd")).click();
    vars.put("win2191", waitForWindow(2000));
    driver.switchTo().window(vars.get("win2191").toString());
  }
}
